title: DeBakey VA vascular
theme: "just-the-docs"
color_scheme: "light"               # "dark" also available

url: "https://nealbarshes-protocols.github.io"
baseurl: ""  # if deploying to main repo root, else use "/repo-name"

# Search settings (optional)
search_enabled: true
search.heading: Search
search.placeholder: Search docs

# Footer
footer_content: "© VA Team 2025 | For internal VA use only"

# Just the Docs GitHub Pages compatibility
plugins:
  - jekyll-feed

# Exclude these files from the build (edit as needed)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

# If you want to add Google Analytics (optional)
# ga_tracking: UA-XXXXXXXXX-X
